important_features = [
    'NAME_INCOME_TYPE', 'AMT_REQ_CREDIT_BUREAU_MON', 'NAME_EDUCATION_TYPE',
    'FONDKAPREMONT_MODE', 'OCCUPATION_TYPE', 'FLAG_OWN_CAR',
    'REG_CITY_NOT_WORK_CITY', 'REG_REGION_NOT_LIVE_REGION', 'REGION_POPULATION_RELATIVE',
    'AMT_REQ_CREDIT_BUREAU_WEEK', 'REG_REGION_NOT_WORK_REGION', 'AMT_ANNUITY',
    'DAYS_REGISTRATION', 'REGION_RATING_CLIENT_W_CITY', 'FLAG_DOCUMENT_5',
    'NAME_TYPE_SUITE', 'AMT_INCOME_TOTAL', 'FLAG_OWN_REALTY',
    'FLAG_DOCUMENT_13', 'AMT_REQ_CREDIT_BUREAU_YEAR', 'DAYS_ID_PUBLISH',
    'AMT_REQ_CREDIT_BUREAU_HOUR', 'FLAG_WORK_PHONE', 'DAYS_BIRTH',
    'DEF_30_CNT_SOCIAL_CIRCLE', 'EXT_SOURCE_3', 'EXT_SOURCE_2',
    'DAYS_LAST_PHONE_CHANGE', 'FLAG_EMAIL', 'FLAG_DOCUMENT_9',
    'CODE_GENDER', 'DAYS_EMPLOYED', 'REG_CITY_NOT_LIVE_CITY',
    'AMT_GOODS_PRICE', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_11',
    'OBS_30_CNT_SOCIAL_CIRCLE', 'FLAG_PHONE', 'FLAG_DOCUMENT_6'
    ]
